# Global settings for the Scrum Master AI Agent system

# Application Settings
application:
  name: "Scrum Master AI"
  version: "1.0.0"
  description: "AI-powered system for automating Scrum Master functions"
  author: "Your Organization"
  contact: "contact@example.com"
  repository: "https://github.com/yourorg/scrum-master-ai"

# Environment Configuration
environment:
  default: "development"
  development:
    debug: true
    log_level: "DEBUG"
    verbose_output: true
  production:
    debug: false
    log_level: "INFO"
    verbose_output: false
  testing:
    debug: true
    log_level: "DEBUG"
    verbose_output: true

# Model Configuration
models:
  default: "gpt-4-turbo"
  options:
    - name: "gpt-4-turbo"
      temperature: 0.3
      max_tokens: 4096
    - name: "gpt-4-1106-preview"
      temperature: 0.2
      max_tokens: 8192
    - name: "gpt-3.5-turbo-16k"
      temperature: 0.4
      max_tokens: 16384
  fallback: "gpt-3.5-turbo"

# API Configurations
apis:
  trello:
    base_url: "https://api.trello.com/1"
    rate_limit: 100  # requests per minute
    timeout: 30  # seconds
    retry_attempts: 3
    retry_delay: 2  # seconds

  slack:
    base_url: "https://slack.com/api"
    rate_limit: 50  # requests per minute
    timeout: 10  # seconds

# Crew Configuration
crew:
  default_process: "sequential"
  process_options:
    - "sequential"
    - "hierarchical"
    - "parallel"
  max_iterations: 5
  default_verbose: true
  memory_enabled: true
  cache_enabled: true
  cache_ttl: 3600  # seconds

# Reporting Configuration
reporting:
  output_directory: "./reports"
  template_directory: "./templates"
  default_format: "markdown"
  formats:
    - "markdown"
    - "html"
    - "pdf"
  auto_save: true
  version_control: true
  max_archive_reports: 10

# Notification Settings
notifications:
  enabled: true
  channels:
    - "email"
    - "slack"
  email:
    smtp_server: "smtp.example.com"
    port: 587
    use_tls: true
  slack:
    default_channel: "#scrum-reports"

# Logging Configuration
logging:
  file: "./logs/scrum_master_ai.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  rotation: "1 day"
  backup_count: 7